---

nameOverride: "kafka"

kafka:
  enabled: true
  version: 3.5.0
  cluster:
    replicas: 3
  zookeeper:
    replicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 200M
  external_listener:
    enabled: true
    type: route
    tls:
      secret: kafka-tls
      certificate: tls.crt
      privatekey: tls.key
  config:
    autoCreateTopics: false
    defaultReplicationFactor: 3
    offsetsTopicReplicationFactor: 3
    transactionStateLogReplicationFactor: 3
    transactionStateLogMinIsr: 3
    minInsyncReplicas: 2
    interBrokerProtocolVersion: '3.5'
  storage:
    # type: jbod
    # volumes:
    #   - id: 0
    #     type: persistent-claim
    #     size: 50Gi
    #     deleteClaim: true
    type: ephemeral
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 250m
          memory: 250M
    userOperator:
      resources:
        limits:
          cpu: 250m
          memory: 250M
        requests:
          cpu: 150m
          memory: 150M
  resources:
    limits:
      cpu: '1'
      memory: 2G
    requests:
      cpu: 300m
      memory: 500M

namespace:

authentication:
  clientId: admin
  clientSecret: kafkaadmin
  securityProtocol: SASL_PLAINTEXT
  saslMechanism: SCRAM-SHA-512

authorization: simple

argocd:
  enabled: true
  syncwave: "-1"